<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<MiniExcelVersion Condition="'$(MiniExcelVersion)' == ''">source</MiniExcelVersion>
	</PropertyGroup>

	<ItemGroup Condition="'$(MiniExcelVersion)' == 'source'">
		<ProjectReference Include="..\..\src\MiniExcel\MiniExcelLibs.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(MiniExcelVersion)' != 'source'">
		<PackageReference Include="MiniExcel" Version="$(MiniExcelVersion)" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\MiniExcel.Benchmarks\Test1,000,000x10.xlsx"
		      Link="Test1,000,000x10.xlsx"
		      CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>