<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MiniExcel.PlaceInCell.MinimalApis</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MiniExcel.Core\MiniExcel.Core.csproj" />
    <ProjectReference Include="..\..\src\MiniExcel.OpenXml\MiniExcel.OpenXml.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\data\images\github_logo.png" Link="images\github_logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\data\images\google_logo.png" Link="images\google_logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
