name: MiniExcel Benchmarks

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  QueryBenchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./benchmarks/MiniExcel.Benchmarks
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./benchmarks/MiniExcel.Benchmarks
      - name: Benchmark
        run: dotnet run -c Release -f net9.0
        working-directory: ./benchmarks/MiniExcel.Benchmarks
        env:
          BenchmarkMode: Automatic
          BenchmarkSection: query
      - name: Renaming result file
        run: mv MiniExcelLibs.Benchmarks.BenchmarkSections.QueryXlsxBenchmark-report-github.md query-benchmark.md
        working-directory: ./benchmarks/MiniExcel.Benchmarks/BenchmarkDotNet.Artifacts/results
      - name: Save benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: query-benchmark-result
          path: ./benchmarks/MiniExcel.Benchmarks/BenchmarkDotNet.Artifacts/results/*.md

  CreateBenchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./benchmarks/MiniExcel.Benchmarks
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./benchmarks/MiniExcel.Benchmarks
      - name: Benchmark
        run: dotnet run -c Release -f net9.0
        working-directory: ./benchmarks/MiniExcel.Benchmarks
        env:
          BenchmarkMode: Automatic
          BenchmarkSection: create
      - name: Renaming result file
        run: mv MiniExcelLibs.Benchmarks.BenchmarkSections.CreateXlsxBenchmark-report-github.md create-benchmark.md
        working-directory: ./benchmarks/MiniExcel.Benchmarks/BenchmarkDotNet.Artifacts/results
      - name: Save benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: create-benchmark-result
          path: ./benchmarks/MiniExcel.Benchmarks/BenchmarkDotNet.Artifacts/results/*.md

  TemplateBenchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./benchmarks/MiniExcel.Benchmarks
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./benchmarks/MiniExcel.Benchmarks
      - name: Benchmark
        run: dotnet run -c Release -f net9.0
        working-directory: ./benchmarks/MiniExcel.Benchmarks
        env:
          BenchmarkMode: Automatic
          BenchmarkSection: template
      - name: Renaming result file
        run: mv MiniExcelLibs.Benchmarks.BenchmarkSections.TemplateXlsxBenchmark-report-github.md template-benchmark.md
        working-directory: ./benchmarks/MiniExcel.Benchmarks/BenchmarkDotNet.Artifacts/results
      - name: Save benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: template-benchmark-result
          path: ./benchmarks/MiniExcel.Benchmarks/BenchmarkDotNet.Artifacts/results/*.md

  PushBenchmarksResults:
    runs-on: ubuntu-latest
    needs: [ QueryBenchmark, CreateBenchmark, TemplateBenchmark ]
 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch benchmark results
        uses: actions/download-artifact@v4
        with:
          path: ./benchmarks/results
          merge-multiple: true
      - name: Commit reports
        working-directory: ./benchmarks/results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./*.md
          git commit -am "Automated benchmark report - ${{ github.ref_name }}"
          git push origin master --force-with-lease